// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTeamTMA.DBContexts;

namespace ProjectTeamTMA.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ProjectTeamTMA.Model.BookRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("datetime");

                    b.Property<string>("issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("personBookingId")
                        .HasColumnType("int");

                    b.Property<int>("personalApprovedId")
                        .HasColumnType("int");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDay")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime");

                    b.Property<ulong?>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_BookRooms");

                    b.HasIndex("personBookingId");

                    b.HasIndex("roomId")
                        .IsUnique();

                    b.ToTable("BookRoom");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("buildingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Buildings");

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            buildingName = "Toàn nhà 1",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            buildingName = "Toàn nhà 2",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            buildingName = "Toàn nhà 3",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("buildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<string>("floorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Floors");

                    b.HasIndex("buildingId");

                    b.ToTable("Floor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            buildingId = 1,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 1",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            buildingId = 1,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 2",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            buildingId = 1,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 3",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            buildingId = 2,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 1",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            buildingId = 2,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 2",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            buildingId = 2,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorName = "Tầng 3",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("char(100)");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_IdRole");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            roleName = "Admin",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            roleName = "User",
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<int>("floorId")
                        .HasColumnType("int");

                    b.Property<string>("roomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<ulong?>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Rooms");

                    b.HasIndex("floorId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfBeds = 2,
                            area = "40m2",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorId = 1,
                            roomName = "A111",
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            NumberOfBeds = 2,
                            area = "40m2",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorId = 1,
                            roomName = "A112",
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            NumberOfBeds = 2,
                            area = "40m2",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorId = 1,
                            roomName = "A212",
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            NumberOfBeds = 2,
                            area = "40m2",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            floorId = 1,
                            roomName = "A212",
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("createdTime")
                        .HasColumnType("datetime");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<ulong?>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("updatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("roleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            address = "Bình Định",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Võ Lập",
                            passWord = "123123",
                            phone = 37516333,
                            roleId = 1,
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userName = "knvolap"
                        },
                        new
                        {
                            Id = 2,
                            address = "Bình Định",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Văn Tính",
                            passWord = "123123",
                            phone = 37516444,
                            roleId = 2,
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userName = "vantinh"
                        },
                        new
                        {
                            Id = 3,
                            address = "Đà Nẵng",
                            createdTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Thanh Thảo",
                            passWord = "123123",
                            phone = 37516555,
                            roleId = 2,
                            status = 1ul,
                            updatedTime = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userName = "thanhthao"
                        });
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.BookRoom", b =>
                {
                    b.HasOne("ProjectTeamTMA.Model.User", "Users")
                        .WithMany("BookRooms")
                        .HasForeignKey("personBookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjectTeamTMA.Model.Room", "Rooms")
                        .WithOne("BookRooms")
                        .HasForeignKey("ProjectTeamTMA.Model.BookRoom", "roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Floor", b =>
                {
                    b.HasOne("ProjectTeamTMA.Model.Building", "Buildings")
                        .WithMany("Floors")
                        .HasForeignKey("buildingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Room", b =>
                {
                    b.HasOne("ProjectTeamTMA.Model.Floor", "Floors")
                        .WithMany("Rooms")
                        .HasForeignKey("floorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.User", b =>
                {
                    b.HasOne("ProjectTeamTMA.Model.Role", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.Room", b =>
                {
                    b.Navigation("BookRooms");
                });

            modelBuilder.Entity("ProjectTeamTMA.Model.User", b =>
                {
                    b.Navigation("BookRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
